Correccion del cateo dentro del qty | int -> float
Aviles17/Bot_Supertrend pull request #52
Opened 2024-12-19 18:55 UTC by SBoteroP

mero meme mano

2024-12-22 22:28 UTC, Aviles17 commented on config/Credenciales.py
Que hace este archivo acá. Nos van a robar las credenciales y ademas es una archivo de Credenciales viejisimo

2024-12-22 22:29 UTC, Aviles17 commented on scripts/ST_Indicators.py
El llamado a la libreria **math** esta mal escrito en la linea 50 del nuevo archivo, eso totea producción :(

2024-12-22 22:29 UTC, Aviles17 commented on test.py
Que mondas es esto???????

2024-12-22 22:30 UTC, Aviles17 requested changes
Parce subio unos archivos con crdenciales pegadas, un archivo de pruebas vacio y una biblioteca mal escrita ....

2024-12-22 22:37 UTC, SBoteroP reviewed
Listo maestro, revise

2024-12-23 00:11 UTC, Aviles17 approved these changes
Aun no le haga el merge que yo le voy a arreglar algo

2024-12-23 00:19 UTC, Aviles17 approved these changes

2024-12-23 05:43 UTC, merged